AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: twilio lambda
Resources:
  HelloRubyRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: twilio_lambda.hello_world
      Runtime: ruby2.5
      CodeUri: s3://twilio-lambda-guayosr/7ccb4494be09de37d7a618203b5f087d
Outputs:
  HelloRubyRecordFunction:
    Description: Hello Ruby Record Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloRubyRecordFunction
      - Arn
