AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'twilio lambda'

Resources:
  HelloRubyRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: twilio_lambda.hello_world
      Runtime: ruby2.5
      
  TwilioLambdaMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: twilio_lambda.forward_message
      Runtime: ruby2.5
      
  TwilioLambdaCallsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: twilio_lambda.receive_and_record_call
      Runtime: ruby2.5

Outputs:
  HelloRubyRecordFunction:
    Description: Hello Ruby Record Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloRubyRecordFunction
      - Arn
  TwilioLambdaMessageFunction:
    Description: Twilio Lamvda Message Function ARN
    Value:
      Fn::GetAtt:
      - TwilioLambdaMessageFunction
      - Arn
  TwilioLambdaCallsFunction:
    Description: Twilio Lambda Calls Function ARN
    Value:
      Fn::GetAtt:
      - TwilioLambdaCallsFunction
      - Arn